module.exports = {
	siteURL: process.env.URL || 'https://imhgmbh.de',
	siteName: 'IMH GmbH',
	siteDescription: 'IMH GmbH Immobilienmanagement Hoffmann in Bad Kreuznach',
	siteImage: '/assets/images/logo.png',
	lang: 'de',
	locale: 'de_de',
	authorName: 'Sven Hoffmann',
	authorURL: 'sven-hoffmann',
	authorEmail: 'mail@imhgmbh.de',
	twitterSite: '@shanerobinson',
	twitterCreator: '@shanerobinson',
	address: {
		street: 'Guldentaler Weg 8',
		city: 'Bad Kreuznach',
		state: 'Hessen',
		zip: '55545',
		phoneDisplay: '+49 (176) 122-5656',
		phoneCall: '+491761225656',
		email: 'mail@imhgmbh.de',
	},
}
