module.exports = {
	siteURL: process.env.URL || 'https://tsliving.de',
	siteName: 'TSLiving',
	siteDescription: 'TSLiving - Bauen. Sanieren. Perfektionieren.',
	siteImage: '/assets/svg/logo-landscape.svg',
	lang: 'de',
	locale: 'de_de',
	authorName: 'TSLiving Team',
	authorURL: 'team',
	authorEmail: 'info@tsliving.de',
	twitterSite: '@shanerobinson',
	twitterCreator: '@shanerobinson',
	address: {
		street: 'Musterstraße 123',
		city: 'Berlin',
		state: 'Berlin',
		zip: '10115',
		phoneDisplay: '+49 (30) 123-4567',
		phoneCall: '+49301234567',
		email: 'info@tsliving.de',
	},
}
